repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: "https://github.com/gitleaks/gitleaks"
    rev: "v8.24.2"
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: cargo-fmt
        name: "cargo fmt"
        entry: "cargo fmt --all --check"
        language: "system"
        types: ["rust"]
        pass_filenames: false

      - id: cargo-nextest-deboa-compio-default
        name: "test default"
        # Remove exports below if you don't have these tools installed
        entry: bash -c "
          export RUSTC_WRAPPER=kache &&
          export RUSTC_LINKER=clang &&
          export CARGO_BUILD_RUSTFLAGS="-C link-arg=-fuse-ld=mold" &&
          cargo test --doc &&
          cargo nextest run -j1 --package deboa-compio
          "
        language: "system"
        types: ["rust"]
        pass_filenames: false

      - id: cargo-nextest-deboa-compio-http1-native-tls
        name: "test deboa-compio with http1 and native-tls"
        entry: bash -c "
          export RUSTC_WRAPPER=kache &&
          export RUSTC_LINKER=clang &&
          export CARGO_BUILD_RUSTFLAGS="-C link-arg=-fuse-ld=mold" &&
          cargo nextest run --package deboa-compio --features "http1 native-tls easyhttpmock-vetis-compio/http1 easyhttpmock-vetis-compio/rust-tls" --no-default-features
          "
        language: "system"
        types: ["rust"]
        pass_filenames: false

      - id: cargo-nextest-deboa-compio-http2-native-tls
        name: "test deboa-compio with http2' and native-tls"
        entry: bash -c "
          export RUSTC_WRAPPER=kache &&
          export RUSTC_LINKER=clang &&
          export CARGO_BUILD_RUSTFLAGS="-C link-arg=-fuse-ld=mold" &&
          cargo nextest run --package deboa-compio --features "http2 native-tls easyhttpmock-vetis-compio/http2 easyhttpmock-vetis-compio/rust-tls" --no-default-features
          "
        language: "system"
        types: ["rust"]
        pass_filenames: false

      - id: cargo-nextest-deboa-compio-http1-rust-tls
        name: "test deboa-compio with http1 and rust-tls"
        entry: bash -c "
          export RUSTC_WRAPPER=kache &&
          export RUSTC_LINKER=clang &&
          export CARGO_BUILD_RUSTFLAGS="-C link-arg=-fuse-ld=mold" &&
          cargo nextest run --package deboa-compio --features "http1 rust-tls default-rustls-provider default-rustls-verifier easyhttpmock-vetis-compio/http1 easyhttpmock-vetis-compio/rust-tls" --no-default-features
          "
        language: "system"
        types: ["rust"]
        pass_filenames: false

      - id: cargo-nextest-deboa-compio-http3-rust-tls
        name: "test deboa-compio with http3 and rust-tls"
        entry: bash -c "
          export RUSTC_WRAPPER=kache &&
          export RUSTC_LINKER=clang &&
          export CARGO_BUILD_RUSTFLAGS="-C link-arg=-fuse-ld=mold" &&
          cargo nextest run --package deboa-compio --features "http3 rust-tls default-rustls-provider default-rustls-verifier easyhttpmock-vetis-compio/http3 easyhttpmock-vetis-compio/rust-tls" --no-default-features
          "
        language: "system"
        types: ["rust"]
        pass_filenames: false

      - id: cargo-nextest-deboa-smol-default
        name: "test default"
        # Remove exports below if you don't have these tools installed
        entry: bash -c "
          export RUSTC_WRAPPER=kache &&
          export RUSTC_LINKER=clang &&
          export CARGO_BUILD_RUSTFLAGS="-C link-arg=-fuse-ld=mold" &&
          cargo test --doc &&
          cargo nextest run -j1 --package deboa-smol
          "
        language: "system"
        types: ["rust"]
        pass_filenames: false

      - id: cargo-nextest-deboa-smol-http1-native-tls
        name: "test deboa-smol with http1 and native-tls"
        entry: bash -c "
          export RUSTC_WRAPPER=kache &&
          export RUSTC_LINKER=clang &&
          export CARGO_BUILD_RUSTFLAGS="-C link-arg=-fuse-ld=mold" &&
          cargo nextest run --package deboa-smol --features "http1 native-tls easyhttpmock-vetis-smol/http1 easyhttpmock-vetis-smol/rust-tls" --no-default-features
          "
        language: "system"
        types: ["rust"]
        pass_filenames: false

      - id: cargo-nextest-deboa-smol-http2-native-tls
        name: "test deboa-smol with http2' and native-tls"
        entry: bash -c "
          export RUSTC_WRAPPER=kache &&
          export RUSTC_LINKER=clang &&
          export CARGO_BUILD_RUSTFLAGS="-C link-arg=-fuse-ld=mold" &&
          cargo nextest run --package deboa-smol --features "http2 native-tls easyhttpmock-vetis-smol/http2 easyhttpmock-vetis-smol/rust-tls" --no-default-features
          "
        language: "system"
        types: ["rust"]
        pass_filenames: false

      - id: cargo-nextest-deboa-smol-http1-rust-tls
        name: "test deboa-smol with http1 and rust-tls"
        entry: bash -c "
          export RUSTC_WRAPPER=kache &&
          export RUSTC_LINKER=clang &&
          export CARGO_BUILD_RUSTFLAGS="-C link-arg=-fuse-ld=mold" &&
          cargo nextest run --package deboa-smol --features "http1 rust-tls default-rustls-provider default-rustls-verifier easyhttpmock-vetis-smol/http1 easyhttpmock-vetis-smol/rust-tls" --no-default-features
          "
        language: "system"
        types: ["rust"]
        pass_filenames: false

      - id: cargo-nextest-deboa-smol-http3-rust-tls
        name: "test deboa-smol with http3 and rust-tls"
        entry: bash -c "
          export RUSTC_WRAPPER=kache &&
          export RUSTC_LINKER=clang &&
          export CARGO_BUILD_RUSTFLAGS="-C link-arg=-fuse-ld=mold" &&
          cargo nextest run --package deboa-smol --features "http3 rust-tls default-rustls-provider default-rustls-verifier easyhttpmock-vetis-smol/http3 easyhttpmock-vetis-smol/rust-tls" --no-default-features
          "
        language: "system"
        types: ["rust"]
        pass_filenames: false

      - id: cargo-nextest-deboa-tokio-default
        name: "test deboa-tokio"
        entry: bash -c "
          export RUSTC_WRAPPER=kache &&
          export RUSTC_LINKER=clang &&
          export CARGO_BUILD_RUSTFLAGS="-C link-arg=-fuse-ld=mold" &&
          cargo nextest run --package deboa-tokio
          "
        language: "system"
        types: ["rust"]
        pass_filenames: false

      - id: cargo-nextest-deboa-tokio-http1-native-tls
        name: "test deboa-tokio with http1 and native-tls"
        entry: bash -c "
          export RUSTC_WRAPPER=kache &&
          export RUSTC_LINKER=clang &&
          export CARGO_BUILD_RUSTFLAGS="-C link-arg=-fuse-ld=mold" &&
          cargo nextest run --package deboa-tokio --features "http1 native-tls easyhttpmock-vetis-tokio/http1 easyhttpmock-vetis-tokio/rust-tls" --no-default-features
          "
        language: "system"
        types: ["rust"]
        pass_filenames: false

      - id: cargo-nextest-deboa-tokio-http2-native-tls
        name: "test deboa-tokio with http2 and native-tls"
        entry: bash -c "
          export RUSTC_WRAPPER=kache &&
          export RUSTC_LINKER=clang &&
          export CARGO_BUILD_RUSTFLAGS="-C link-arg=-fuse-ld=mold" &&
          cargo nextest run --package deboa-tokio --features "http2 native-tls easyhttpmock-vetis-tokio/http1 easyhttpmock-vetis-tokio/rust-tls" --no-default-features
          "
        language: "system"
        types: ["rust"]
        pass_filenames: false

      - id: cargo-nextest-deboa-tokio-http1-rust-tls
        name: "test deboa-tokio with http1 and rust-tls"
        entry: bash -c "
          export RUSTC_WRAPPER=kache &&
          export RUSTC_LINKER=clang &&
          export CARGO_BUILD_RUSTFLAGS="-C link-arg=-fuse-ld=mold" &&
          cargo nextest run --package deboa-tokio --features "http1 rust-tls default-rustls-provider default-rustls-verifier easyhttpmock-vetis-tokio/http1 easyhttpmock-vetis-tokio/rust-tls" --no-default-features
          "
        language: "system"
        types: ["rust"]
        pass_filenames: false

      - id: cargo-nextest-deboa-tokio-http3-rust-tls
        name: "test deboa-tokio with http3 and rust-tls"
        entry: bash -c "
          export RUSTC_WRAPPER=kache &&
          export RUSTC_LINKER=clang &&
          export CARGO_BUILD_RUSTFLAGS="-C link-arg=-fuse-ld=mold" &&
          cargo nextest run --package deboa-tokio --features "http3 rust-tls default-rustls-provider default-rustls-verifier easyhttpmock-vetis-tokio/http3 easyhttpmock-vetis-tokio/rust-tls" --no-default-features
          "
        language: "system"
        types: ["rust"]
        pass_filenames: false


  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        # Optional: Add --fix to automatically correct format violations
        args: ["--fix"]
