[package]
name = "vamo-macros"
edition = "2021"
version = "0.0.2-beta.3"
authors = ["Rogerio Araújo <rogerio.araujo@gmail.com>"]
description = "macros for vamo"
license = "MIT"
repository = "https://github.com/ararog/deboa"
readme = "README.md"
keywords = ["compiler-plugin"]
exclude = [".travis.yml"]
publish = true
rust-version = "1.64.0"

[lib]
proc-macro = true

[dependencies]
deboa = { path = "../deboa", version = "0.0.6-beta.9", features = ["http1"] }
deboa-extras = { path = "../deboa-extras", version = "0.0.2-beta.4", features=["json"] }
vamo = { path = "../vamo", version = "0.0.2-beta.3" }
proc-macro2 = "1.0.101"
serde = "1.0.228"
syn = { version = "2.0", features = ["full"] }
quote = "1.0.41"
http = "1.3.1"

[dev-dependencies]
deboa-tests = { path = "../deboa-tests", version = "0.0.1" }
httpmock = { version = "0.8.2", features = ["http2"] }
tokio = { version = "1.47.2", features = ["rt-multi-thread"] }
