[package]
name = "vamo-macros"
edition = "2021"
version = "0.0.1"
authors = ["Rogerio Araújo <rogerio.araujo@gmail.com>"]
description = "vamo macros for vamo"
license = "MIT"
repository = "https://github.com/ararog/deboa"
readme = "README.md"
keywords = ["compiler-plugin"]
exclude = [".travis.yml"]
publish = true
rust-version = "1.64.0"

[lib]
proc-macro = true

[dependencies]
deboa = { path = "../deboa", version = "0.0.5-beta.3", features = ["http1"] }
vamo = { path = "../vamo", version = "0.0.1-beta.3" }
proc-macro2 = "1.0.101"
tokio = { version = "1.47.1", features = ["full"] }
serde = "1.0.219"
syn = { version = "2.0", features = ["full"] }
quote = "1.0.40"

[dev-dependencies]
deboa-tests = { path = "../deboa-tests", version = "0.0.1" }