[package]
name = "deboa"
version = "0.0.5-alpha.1"
edition = "2024"
authors = ["Rogerio Araújo <rogerio.araujo@gmail.com>"]
repository = "https://github.com/ararog/deboa"
homepage = "https://github.com/ararog/deboa"
description = "A friendly rest client on top of hyper."
readme = "README.md"
license = "MIT"
keywords = ["http", "networking", "client", "fetch", "rest-client"]
publish = true

[features]
default = ["tokio-rt"]

# runtimes
tokio-rt = ["http1", "http2", "dep:tokio"]
smol-rt = [
  "http1",
  "http2",
  "dep:smol",
  "dep:async-native-tls",
  "dep:smol-hyper",
  "dep:async-executor",
  "dep:smol-macros",
  "dep:macro_rules_attribute",
]

# protocols
http1 = []
http2 = []

[dependencies]
async-executor = { version = "1.13.3", optional = true }
async-native-tls = { version = "0.5.0", optional = true }
async-trait = "0.1.89"
base64 = "0.22.1"
bytes = { version = "1.2", optional = false }
futures = "0.3.31"
http = "1"
http-body = "1"
http-body-util = "0.1"
hyper = { version = "1.6.0", features = ["client", "http1", "http2"] }
hyper-util = { version = "0.1.10", features = [
  "http1",
  "http2",
  "client",
  "client-legacy",
  "tokio",
] }
macro_rules_attribute = { version = "0.2.2", optional = true }
mime = { version = "0.3.17" }
serde = { version = "1.0.217", features = ["derive"] }
smol = { version = "2.0.2", optional = true }
smol-hyper = { version = "0.1.0", optional = true, features = ["smol"]}
smol-macros = { version = "0.1.1", optional = true }
strum_macros = "0.27.0"
thiserror = "2.0.16"
tokio = { version = "1.43.1", features = ["full"], optional = true }
typed-builder = "0.21.2"
url = "2.5.4"

[dev-dependencies]
criterion = { version = "0.7.0", features = [
  "html_reports",
  "async",
  "async_smol",
  "async_tokio"
] }
httpmock = { version = "0.8.0-alpha.1", features = ["http2"] }
smol = "2.0.2"
tokio = { version = "1", features = ["full"] }

[[bench]]
name = "deboa_benchmark"
harness = false
