[package]
name = "deboa"
version = "0.0.6-beta.3"
edition = "2021"
authors = ["Rogerio Araújo <rogerio.araujo@gmail.com>"]
repository = "https://github.com/ararog/deboa"
homepage = "https://github.com/ararog/deboa"
description = "A friendly rest client on top of hyper."
readme = "README.md"
license = "MIT"
keywords = ["http", "networking", "client", "fetch", "rest-client"]
publish = true
rust-version = "1.64.0"

[features]
default = ["tokio-rt"]

# runtimes
tokio-rt = ["http1", "http2", "dep:tokio", "dep:tokio-native-tls"]
smol-rt = [
  "http1",
  "http2",
  "dep:smol",
  "dep:async-native-tls",
  "dep:smol-hyper",
  "dep:async-executor",
  "dep:smol-macros",
  "dep:macro_rules_attribute",
]

# protocols
http1 = []
http2 = []

[dependencies]
async-executor = { version = "1.13.3", optional = true }
async-native-tls = { version = "0.5.0", optional = true }
async-trait = "0.1.89"
base64 = "0.22.1"
bytes = { version = "1.2", optional = false }
cookie = "0.18.1"
futures = "0.3.31"
http = "1"
http-body = "1"
http-body-util = "0.1"
hyper = { version = "1.6.0", features = ["client", "http1", "http2"] }
hyper-util = { version = "0.1.10", features = [
  "http1",
  "http2",
  "client",
  "client-legacy",
  "tokio",
] }
indexmap = "2.11.4"
macro_rules_attribute = { version = "0.2.2", optional = true }
mime = { version = "0.3.17" }
mockall = "0.13.1"
rand = "0.9.2"
serde = { version = "1.0.217", features = ["derive"] }
smol = { version = "2.0.2", optional = true }
smol-hyper = { version = "0.1.0", optional = true, features = ["smol"]}
smol-macros = { version = "0.1.1", optional = true }
strum_macros = "0.27.0"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["rt-multi-thread"], optional = true }
tokio-native-tls = { version = "0.3.1", optional = true }
typed-builder = "0.21.2"
url = "2.5.4"
urlencoding = "2.1.3"

[dev-dependencies]
deboa-tests = { path = "../deboa-tests", version = "0.0.1" }
criterion = { version = "0.7.0", features = [
  "html_reports",
  "async",
  "async_smol",
  "async_tokio"
] }
httpmock = { version = "0.8.0-alpha.1", features = ["http2"] }
smol = "2.0.2"

[[bench]]
name = "deboa_benchmark"
harness = false
