[package]
name = "bora"
version = "0.0.1-alpha.1"
edition = "2024"
publish = true

[dependencies]
deboa = { path = "../deboa", features = ["http1"] }
deboa-extras = { path = "../deboa-extras", features = ["json"] }
http = "1.3.1"
