[package]
name = "deboa-tls"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = [
  "rust-tls",
  "default-rustls-provider",
  "default-rustls-verifier",
]

rust-tls = [
  "rustls/tls12",
  "dep:rustls-native-certs",
  "dep:futures-rustls",
  "dep:rustls-pki-types",
]
native-tls= []

default-rustls-verifier = ["__webpki_rustls_verifier"]
webpki-rustls-verifier = ["__webpki_rustls_verifier"]
platform-rustls-verifier = ["__platform_rustls_verifier"]
__webpki_rustls_verifier = ["dep:webpki-roots"]
__platform_rustls_verifier = ["dep:rustls-platform-verifier"]

# rustls providers
default-rustls-provider = ["__rustls_aws_lc_rs"]
no-provider = []
aws-lc-rustls-provider = ["__rustls_aws_lc_rs"]
ring-rustls-provider = ["__rustls_ring"]

__rustls_aws_lc_rs = ["rustls/aws-lc-rs"]
__rustls_ring = ["rustls/ring"]

tcp = []
quic = []

[dependencies]
deboa = { workspace = true }
futures-rustls = { workspace = true, optional = true }
rustls = { workspace = true, optional = true }
rustls-native-certs = { workspace = true, optional = true }
rustls-pki-types = { workspace = true, optional = true }
rustls-platform-verifier = { workspace = true, optional = true }
webpki-roots = { workspace = true, optional = true }
