[package]
name = "deboa-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
deboa = { path = "../deboa" }
http = "1.3.1"
httpmock = { version = "0.8.0-alpha.1", features = ["http2"] }
mime = "0.3.17"
url = "2.5.7"
