[package]
name = "deboa-tests"
version = "0.0.1"
edition = "2021"
authors = ["Rogerio Araújo <rogerio.araujo@gmail.com>"]
repository = "https://github.com/ararog/deboa"
homepage = "https://github.com/ararog/deboa"
description = "Tests for deboa"
readme = "README.md"
license = "MIT"
keywords = ["http", "networking", "client", "fetch", "rest-client"]
publish = false
rust-version = "1.64.0"

[dependencies]
http = "1.3.1"
httpmock = { version = "0.8.1", features = ["http2"] }
mime = "0.3.17"
serde = "1.0.226"
serde_json = "1.0.145"
url = "2.5.7"
