[package]
name = "vamo"
version = "0.0.1-beta.2"
edition = "2024"
authors = ["Rogerio Araújo <rogerio.araujo@gmail.com>"]
repository = "https://github.com/ararog/deboa"
homepage = "https://github.com/ararog/deboa"
description = "A rest wrapper for deboa."
readme = "README.md"
license = "MIT"
keywords = ["http", "networking", "client", "fetch", "rest-client"]
publish = true

[dependencies]
deboa = { path = "../deboa", version = "0.0.5-beta.2", features = ["http1"] }
deboa-extras = { path = "../deboa-extras", version = "0.0.1-beta.2", features = ["json"] }
http = "1.3.1"
url = "2.5.7"

[dev-dependencies]
httpmock = "0.7.0"
tokio = "1.47.1"
