[package]
name = "vamo"
version = "0.0.2-beta.1"
edition = "2021"
authors = ["Rogerio Araújo <rogerio.araujo@gmail.com>"]
repository = "https://github.com/ararog/deboa"
homepage = "https://github.com/ararog/deboa"
description = "A rest wrapper for deboa."
readme = "README.md"
license = "MIT"
keywords = ["http", "networking", "client", "fetch", "rest-client"]
publish = true
rust-version = "1.64.0"

[dependencies]
deboa = { path = "../deboa", version = "0.0.6-beta.5", features = ["http1"] }
deboa-extras = { path = "../deboa-extras", version = "0.0.2-beta.1", features = ["json"] }
http = "1.3.1"
serde = "1.0.228"
url = "2.5.7"

[dev-dependencies]
deboa-tests = { path = "../deboa-tests", version = "0.0.1" }
httpmock = { version = "0.8.1", features = ["http2"] }
tokio = { version = "1.47.1", features = ["rt-multi-thread"] }

