[package]
name = "vamo"
version = "0.0.1-alpha.1"
edition = "2024"
authors = ["Rogerio Araújo <rogerio.araujo@gmail.com>"]
repository = "https://github.com/ararog/deboa"
homepage = "https://github.com/ararog/deboa"
description = "A rest wrapper for deboa."
readme = "README.md"
license = "MIT"
keywords = ["http", "networking", "client", "fetch", "rest-client"]
publish = true

[dependencies]
deboa = { path = "../deboa", features = ["http1"] }
deboa-extras = { path = "../deboa-extras", features = ["json"] }
http = "1.3.1"
