[package]
name = "deboa-h3"
version = "0.1.2"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "H3 support for deboa"
readme.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = []
generic = ["dep:h3", "dep:h3-quinn", "hyper-body-utils/generic-h3", "hyper-body-utils/generic"]
compio = ["dep:h3", "dep:compio-quic", "hyper-body-utils/compio-h3", "hyper-body-utils/compio"]

[dependencies]
bytes = { workspace = true }
compio-quic = { version = "0.8.0", optional = true, default-features = false }
deboa = { workspace = true }
h3 = { workspace = true, optional = true }
h3-quinn = { workspace = true, optional = true }
http = { workspace = true }
http-body-util =  { workspace = true }
hyper-body-utils = { workspace = true, optional = true, default-features = false }
