[package]
name = "deboa-h3"
version = "0.1.1-beta.1"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "H3 support for deboa"
readme.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = []
generic = ["dep:h3", "dep:h3-quinn", "hyper-body-utils/http3", "hyper-body-utils/generic"]
compio = ["dep:h3", "dep:compio-quic", "hyper-body-utils/http3", "hyper-body-utils/compio"]

[dependencies]
bytes = { version = "1.11" }
compio-quic = { version = "0.8.0", optional = true, default-features = false }
deboa = { version = ">= 0.1.0-beta.21"}
h3 = { version = "0.0.8", optional = true, default-features = false }
h3-quinn = { version = "0.0.10", optional = true, default-features = false }
http = { version = "1.4.2", default-features = false }
hyper-body-utils = { workspace = true, optional = true, default-features = false }
