[package]
name = "sse"
version = "0.1.0"
edition = "2024"

[dependencies]
deboa = { version = "0.0.6-beta.6", path = "../../deboa" }
deboa-extras = { version = "0.0.2-beta.1", path = "../../deboa-extras" }
http = "1.3.1"
http-body-util = "0.1.3"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
