title: Deboa
baseurl: "/deboa" # the subpath of your site, e.g. /blog
url: "https://ararog.github.io" # the base hostname & protocol for your site

theme: just-the-docs

markdown: kramdown

plugins:
  - jekyll-default-layout
  - jekyll-sitemap
  - jekyll-feed

color_scheme: dark

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      toc: true
      toc_sticky: true
      sidebar:
        nav: "navigation"

nav_enabled: true 
