source "https://rubygems.org"

gem "jekyll"
gem "json"

group :jekyll_plugins do
  gem "just-the-docs"
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"  
  gem "jekyll-default-layout"
  gem "jekyll-remote-theme"
end
