name: Rust

permissions:
  contents: read
  
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - uses: Swatinem/rust-cache@v2

    - name: Run all tests on all crates
      run: |
        cd deboa-extras
        cargo test --features "serialization_all compression_all"
        cd ..

        cd deboa-fory
        cargo test
        cd ..

        cd deboa-macros
        cargo test
        cd ..

        cd vamo
        cargo test
        cd ..

        cd vamo-macros
        cargo test
        cd ..
        
    - name: Run all HTTP1 tests with native TLS
      run: |
        cd deboa
        cargo test --features "http1 tokio-rt tokio-native-tls" --no-default-features
        cargo test --features "http1 smol-rt smol-native-tls" --no-default-features

    - name: Run all HTTP2 tests with native TLS
      run: |
        cd deboa
        cargo test --features "http2 tokio-rt tokio-native-tls" --no-default-features
        cargo test --features "http2 smol-rt smol-native-tls" --no-default-features

    - name: Run all HTTP1 tests with rust TLS
      run: |
        cd deboa
        cargo test --features "http1 tokio-rt tokio-rust-tls" --no-default-features
        cargo test --features "http1 smol-rt smol-rust-tls" --no-default-features

    - name: Run all HTTP2 tests with rust TLS
      run: |
        cd deboa
        cargo test --features "http2 tokio-rt tokio-rust-tls" --no-default-features
        cargo test --features "http2 smol-rt smol-rust-tls" --no-default-features

    - name: Run all HTTP3 tests with rust TLS
      run: |
        cd deboa
        cargo test --features "http3 tokio-rt tokio-rust-tls" --no-default-features
        cargo test --features "http3 smol-rt smol-rust-tls" --no-default-features

  build-android:
    runs-on: ubuntu-latest
    container: instrumentisto/cargo-ndk
    steps:
    - uses: actions/checkout@v6

    - name: Install Rust toolchains
      run: rustup target add aarch64-linux-android armv7-linux-androideabi

    - uses: Swatinem/rust-cache@v2

    - name: Build for aarch64-linux-android with cargo-ndk
      run: |
        cargo ndk --target armv7-linux-androideabi,aarch64-linux-android,i686-linux-android,x86_64-linux-android build

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6

    - uses: Swatinem/rust-cache@v2
    
    - name: Run all tests on all crates
      run: |
        cd deboa-extras
        cargo test --features "serialization_all compression_all"
        cd ..

        cd deboa-macros
        cargo test
        cd ..

        cd vamo
        cargo test
        cd ..

        cd vamo-macros
        cargo test
        cd ..
              
    # - name: Run all HTTP1 tests with native TLS
    #   run: |
    #     cd deboa
    #     cargo test --features "http1 tokio-rt tokio-native-tls" --no-default-features
    #     cargo test --features "http1 smol-rt smol-native-tls" --no-default-features

    # - name: Run all HTTP2 tests with native TLS
    #   run: |
    #     cd deboa
    #     cargo test --features "http2 tokio-rt tokio-native-tls" --no-default-features
    #     cargo test --features "http2 smol-rt smol-native-tls" --no-default-features

    - name: Run all HTTP1 tests with rust TLS
      run: |
        cd deboa
        cargo test --features "http1 tokio-rt tokio-rust-tls" --no-default-features
        cargo test --features "http1 smol-rt smol-rust-tls" --no-default-features

    - name: Run all HTTP2 tests with rust TLS
      run: |
        cd deboa
        cargo test --features "http2 tokio-rt tokio-rust-tls" --no-default-features
        cargo test --features "http2 smol-rt smol-rust-tls" --no-default-features

    - name: Run all HTTP3 tests with rust TLS
      run: |
        cd deboa
        cargo test --features "http3 tokio-rt tokio-rust-tls" --no-default-features
        cargo test --features "http3 smol-rt smol-rust-tls" --no-default-features

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6

    - name: Install Rust toolchains
      run: rustup target add x86_64-apple-darwin

    - uses: Swatinem/rust-cache@v2

    - name: Build for x86_64-apple-darwin
      run: cargo build --target x86_64-apple-darwin --release
    
    - name: Run all tests on all crates
      run: |
        cd deboa-extras
        cargo test --features "serialization_all compression_all"
        cd ..

        cd deboa-fory
        cargo test
        cd ..

        cd deboa-macros
        cargo test
        cd ..

        cd vamo
        cargo test
        cd ..

        cd vamo-macros
        cargo test
        cd ..
              
    # - name: Run all HTTP1 tests with native TLS
    #   run: |
    #     cd deboa
    #     cargo test --features "http1 tokio-rt tokio-native-tls" --no-default-features
    #     cargo test --features "http1 smol-rt smol-native-tls" --no-default-features

    # - name: Run all HTTP2 tests with native TLS
    #   run: |
    #     cd deboa
    #     cargo test --features "http2 tokio-rt tokio-native-tls" --no-default-features
    #     cargo test --features "http2 smol-rt smol-native-tls" --no-default-features

    - name: Run all HTTP1 tests with rust TLS
      run: |
        cd deboa
        cargo test --features "http1 tokio-rt tokio-rust-tls" --no-default-features
        cargo test --features "http1 smol-rt smol-rust-tls" --no-default-features

    - name: Run all HTTP2 tests with rust TLS
      run: |
        cd deboa
        cargo test --features "http2 tokio-rt tokio-rust-tls" --no-default-features
        cargo test --features "http2 smol-rt smol-rust-tls" --no-default-features

    - name: Run all HTTP3 tests with rust TLS
      run: |
        cd deboa
        cargo test --features "http3 tokio-rt tokio-rust-tls" --no-default-features
        cargo test --features "http3 smol-rt smol-rust-tls" --no-default-features
